-- Code generated by "athena_schema -type=User,Post ./fixture/user.go"; DO NOT EDIT

CREATE external TABLE user (
  `user_id` INT
  `name` STRING
)
CREATE external TABLE post (
  `author_info` 
  `comments` 
  `created_at` timestamp
  `updated_at` timestamp
)
