-- Code generated by "athena_schema -type User,Post ./fixture/"; DO NOT EDIT

CREATE EXTERNAL TABLE IF NOT EXISTS `user` (
  `user_id` int,
  `name` string
) PARTITIONED BY (
  `year` int,
  `month` int,
  `day` int
)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
LOCATION 's3://bucket/user'
;
CREATE EXTERNAL TABLE IF NOT EXISTS `post` (
  `author_info` struct<user_id: int, name: string>,
  `comments` array<struct<text: string, author_info: struct<user_id: int, name: string>>>,
  `created_at` timestamp,
  `updated_at` timestamp
) PARTITIONED BY (
  `year` int,
  `month` int,
  `day` int
)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
LOCATION 's3://bucket/post'
;
